### ISSUE TITLE
Exception: There is empty items in the path

### ISSUE THREAD

**Issue by LoulG** [sergeyzwezdin/magic-chunks#11]
When transforming an XML from the sources, the task breaks with the following:

System.Management.Automation.MethodInvocationException: Exception calling "Transform" with "4" argument(s): "There is empty items in the path.
Parameter name: path" ---> System.ArgumentException: There is empty items in the path.
Parameter name: path
at MagicChunks.Documents.XmlDocument.ReplaceKey(String[] path, String value)
at MagicChunks.Core.Transformer.Transform(IDocument source, TransformationCollection transformations)
at MagicChunks.TransformTask.Transform(String type, String sourcePath, String targetPath, TransformationCollection transformation)
at CallSite.Target(Closure , CallSite , Type , Object , Object , Object , Object )
--- End of inner exception stack trace ---
at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by sergeyzwezdin** [comment]
Do you use MagicChunks as VSTS extension?
Could you share XML which breaks transformation process?

**Comment by sergeyzwezdin** [comment]
Closing issue as still have no response. Feel free to re-open if issue still persists.

**Comment by stromblom** [comment]
I'm getting this. Running MC from Cake.

```xml
<Project>
  <PropertyGroup>
    <publishUrl>C:\Temp</publishUrl>
  </PropertyGroup>
</Project>
```

```c#
            var originalPublishProfile = $"./{webSite}/Properties/PublishProfiles/ToFileSystem.pubxml";

            TransformConfig(originalPublishProfile,
                new TransformationCollection 
                { { "/Project/PropertyGroup/publishUrl", publishUrl } });
```

**Comment by sergeyzwezdin** [comment]
@stromblom 
Actually, this library does not use XPath. It something like "XPath like syntax"
So, removing `/` in the beginning solves the problem?

**Comment by stromblom** [comment]
Okay. Yes that worked like a charm.

**Comment by sergeyzwezdin** [comment]
Nice to hear.

**Comment by amccool** [comment]
> @stromblom
> Actually, this library does not use XPath. It something like "XPath like syntax"
> So, removing `/` in the beginning solves the problem?

I didnt see this in the wiki... any chance to make it stand out?
