### ISSUE TITLE
MagicChunks does not work when Cake.Json is also being used

### ISSUE THREAD

**Issue by bibodha** [sergeyzwezdin/magic-chunks#13]
When you have both Cake.Json and MagicChunks as addins, it throws this exception

`Error: Roslyn.Compilers.CompilationErrorException: (2344,29): error CS0433: The type 'Newtonsoft.Json.Linq.JObject' exists in both 'MagicChunks, Version=1.1.0.34, Culture=neutral, PublicKeyToken=null' and 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Roslyn.Scripting.CommonScriptEngine.CompilationError(DiagnosticBag localDiagnostics, DiagnosticBag diagnostics)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, DiagnosticBag diagnostics, Session session, Type delegateType, Type returnType, CancellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, CommonCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary'2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
`

To reproduce, just take the demo repository from cake "getting started" guide. In the cake file, add "Cake.Json" and "MagicChunks" as #addin and run the default script. Compilation will fail.

**Comment by sergeyzwezdin** [comment]
Fixed as part of `1.2`.

**Comment by sergeyzwezdin** [comment]
Build `1.2` has been shipped.
