### ISSUE TITLE
Visual studio team services: Errors.

### ISSUE THREAD

**Issue by GitWessel** [sergeyzwezdin/magic-chunks#62]
I'm getting the following erros on my vsts release: 
Can anyone tell me what I do wrong? 

2018-04-25T09:14:23.5552784Z ##[error]System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
2018-04-25T09:14:23.5552784Z    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2018-04-25T09:14:23.5552784Z    at System.Reflection.Assembly.GetTypes()
2018-04-25T09:14:23.5552784Z    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
2018-04-25T09:14:23.5552784Z    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
2018-04-25T09:14:23.5552784Z    at System.Management.Automation.CommandProcessorBase.Complete()
2018-04-25T09:14:23.5865335Z ##[error]System.ArgumentException: Invalid JSON primitive: .
2018-04-25T09:14:23.5865335Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2018-04-25T09:14:23.5865335Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2018-04-25T09:14:23.5865335Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
2018-04-25T09:14:23.5865335Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2018-04-25T09:14:23.5865335Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2018-04-25T09:14:23.5865335Z    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2018-04-25T09:14:23.5865335Z    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2018-04-25T09:14:23.5865335Z    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2018-04-25T09:14:23.5865335Z    at System.Management.Automation.CommandProcessorBase.Complete()
2018-04-25T09:14:23.6021620Z ##[error]System.Management.Automation.CmdletInvocationException: Invalid JSON primitive: . ---> System.ArgumentException: Invalid JSON primitive: .
2018-04-25T09:14:23.6021620Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2018-04-25T09:14:23.6021620Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2018-04-25T09:14:23.6021620Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
2018-04-25T09:14:23.6021620Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2018-04-25T09:14:23.6021620Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2018-04-25T09:14:23.6021620Z    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2018-04-25T09:14:23.6021620Z    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2018-04-25T09:14:23.6021620Z    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2018-04-25T09:14:23.6021620Z    at System.Management.Automation.CommandProcessorBase.Complete()
2018-04-25T09:14:23.6021620Z    --- End of inner exception stack trace ---
2018-04-25T09:14:23.6021620Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-04-25T09:14:23.6021620Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-04-25T09:14:23.6021620Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-04-25T09:14:23.6021620Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-04-25T09:14:23.6021620Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-04-25T09:14:23.6021620Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-04-25T09:14:23.6177815Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by lonesomegeek** [comment]
updating to net 4.7 does the trick

**Comment by wallyhall** [comment]
I've tried updating to 4.7, it made no difference for me.

**Comment by kieronlanning** [comment]
We can't update, we have this issue through the release pipeline, so the product is already built.

Oddly enough, it works deploying to our test environment, but fails on all the others - the point at which this runs is identical on each environment, and it's the first thing it does.
