### ISSUE TITLE
Could not load file or assembly 'System.IO.FileSystem' with 2.*

### ISSUE THREAD

**Issue by PingPongSet** [sergeyzwezdin/magic-chunks#83]
I have got the issue below when I try to deploy an ASP.NET Core API app using Config Transform task for Azure DevOps . https://marketplace.visualstudio.com/items?itemName=sergeyzwezdin.magic-chunks

Versions:

2.* exception:
1.*: works without exception

Error below:

2019-01-03T11:34:17.4824394Z ##[section]Starting: Config transform
2019-01-03T11:34:17.4826937Z ==============================================================================
2019-01-03T11:34:17.4826981Z Task         : Config transformation
2019-01-03T11:34:17.4827020Z Description  : Transform config file with Magic Chunks
2019-01-03T11:34:17.4827044Z Version      : 2.0.3
2019-01-03T11:34:17.4827082Z Author       : Sergey Zwezdin
2019-01-03T11:34:17.4827105Z Help         : [More Information](https://github.com/sergeyzwezdin/magic-chunks)
2019-01-03T11:34:17.4827145Z ==============================================================================
2019-01-03T11:34:17.5133477Z Preparing task execution handler.
2019-01-03T11:34:18.2841219Z Executing the powershell script: C:\agent\A4\_work\_tasks\MagicChunks_985284e0-a7d2-4e4d-802c-0a516bffaadf\2.0.3\transform.ps1
2019-01-03T11:34:18.2841828Z  "Config": "azure.config.json"
2019-01-03T11:34:18.2841871Z })
2019-01-03T11:34:18.8746351Z ##[error]System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
2019-01-03T11:34:18.8753766Z    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2019-01-03T11:34:18.8753833Z    at System.Reflection.Assembly.GetTypes()
2019-01-03T11:34:18.8753894Z    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
2019-01-03T11:34:18.8812441Z    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
2019-01-03T11:34:18.8812484Z    at System.Management.Automation.CommandProcessorBase.Complete()
2019-01-03T11:34:18.9451653Z Transformation found: Config: azure.config.json
2019-01-03T11:34:18.9451979Z 
2019-01-03T11:34:18.9452010Z 
2019-01-03T11:34:19.0184350Z Transforming file C:\agent\A4\_work\r1\a\MyApp\appsettings.json
2019-01-03T11:34:19.0184659Z 
2019-01-03T11:34:19.0184691Z 
2019-01-03T11:34:19.0602223Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "Transform" with "4" argument(s): "Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified." ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2019-01-03T11:34:19.0602627Z    at MagicChunks.TransformTask.Transform(String type, String sourcePath, String targetPath, TransformationCollection transformation)
2019-01-03T11:34:19.0602674Z    at CallSite.Target(Closure , CallSite , Type , Object , Object , Object , Object )
2019-01-03T11:34:19.0602707Z    --- End of inner exception stack trace ---
2019-01-03T11:34:19.0602758Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-01-03T11:34:19.0602802Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-01-03T11:34:19.0602836Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-03T11:34:19.0602870Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-03T11:34:19.0834987Z ##[error]PowerShell script completed with 2 errors.
2019-01-03T11:34:19.0840507Z ##[section]Finishing: Config transform

**Comment by dazinator** [comment]
Same problem.

Here is my step:

![image](https://user-images.githubusercontent.com/3176632/51251315-edf8c780-1990-11e9-80d6-b72f167fbc75.png)

Here is the log:

> 2019-01-16T13:05:52.9723705Z ##[section]Starting: Configure for Demo Org
2019-01-16T13:05:52.9728157Z ==============================================================================
2019-01-16T13:05:52.9728208Z Task         : Config transformation
2019-01-16T13:05:52.9728256Z Description  : Transform config file with Magic Chunks
2019-01-16T13:05:52.9728289Z Version      : 2.0.3
2019-01-16T13:05:52.9728321Z Author       : Sergey Zwezdin
2019-01-16T13:05:52.9728370Z Help         : [More Information](https://github.com/sergeyzwezdin/magic-chunks)
2019-01-16T13:05:52.9728403Z ==============================================================================
2019-01-16T13:05:52.9872263Z Preparing task execution handler.
2019-01-16T13:05:53.4198455Z Executing the powershell script: C:\azagent\A1\_work\_tasks\MagicChunks_985284e0-a7d2-4e4d-802c-0a516bffaadf\2.0.3\transform.ps1
2019-01-16T13:05:53.4200568Z "Foo/SigningCertPath": "C:\Program Files\*****\****\*****\Unstable/foo-demo-org.pfx",
2019-01-16T13:05:53.4200744Z "SigningCertPassword": "***"
2019-01-16T13:05:53.4200783Z })
2019-01-16T13:05:53.7393817Z ##[error]System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
2019-01-16T13:05:53.7394365Z    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2019-01-16T13:05:53.7394461Z    at System.Reflection.Assembly.GetTypes()
2019-01-16T13:05:53.7394517Z    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
2019-01-16T13:05:53.7394713Z    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
2019-01-16T13:05:53.7394891Z    at System.Management.Automation.CommandProcessorBase.Complete()
2019-01-16T13:05:53.7900353Z Transformation found: Foo/SigningCertPath: C:\Program Files\Foo\Bar\Baz\Unstable/foo-demo-org.pfx
2019-01-16T13:05:53.7900639Z 
2019-01-16T13:05:53.7901371Z 
2019-01-16T13:05:53.7947624Z Transformation found: SigningCertPassword: ***
2019-01-16T13:05:53.7947852Z 
2019-01-16T13:05:53.7947957Z 
2019-01-16T13:05:53.8087469Z Transforming file C:\Program Files\Foo\Bar\Baz\Unstable\appsettings-foo-Demo.json
2019-01-16T13:05:53.8087646Z 
2019-01-16T13:05:53.8087808Z 
2019-01-16T13:05:53.9137633Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "Transform" with "4" argument(s): "Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified." ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2019-01-16T13:05:53.9138147Z    at MagicChunks.TransformTask.Transform(String type, String sourcePath, String targetPath, TransformationCollection transformation)
2019-01-16T13:05:53.9138452Z    at CallSite.Target(Closure , CallSite , Type , Object , Object , Object , Object )
2019-01-16T13:05:53.9138659Z    --- End of inner exception stack trace ---
2019-01-16T13:05:53.9138743Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-01-16T13:05:53.9138864Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-01-16T13:05:53.9138917Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T13:05:53.9138966Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T13:05:53.9615065Z ##[error]PowerShell script completed with 2 errors.
2019-01-16T13:05:53.9622559Z ##[section]Finishing: Configure for Demo Org

**Comment by jskumar** [comment]
@sergeyzwezdin,
Tools is extremely useful, where used in many agents. Thanks

But suddenly after installed dotnet 2.2; below problem still persists. Help to resolve this would be highly appreciated.

Let know any additional details required.

============================
2019-02-06T07:59:41.8047786Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "Transform" with "4" argument(s): "**Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0,** Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified." ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2019-02-06T07:59:41.8048176Z    at MagicChunks.TransformTask.Transform(String type, String sourcePath, String targetPath, TransformationCollection transformation)
2019-02-06T07:59:41.8048231Z    at CallSite.Target(Closure , CallSite , Type , Object , Object , Object , Object )
2019-02-06T07:59:41.8048300Z    --- End of inner exception stack trace ---
2019-02-06T07:59:41.8048345Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-02-06T07:59:41.8048390Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-02-06T07:59:41.8048433Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-06T07:59:41.8048492Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-06T07:59:41.8298028Z ##[error]PowerShell script completed with 2 errors.

**Comment by SirBisgaard** [comment]
I have had this problem as well, with one of our older agents.
I fixed it by installing .NET 4.7.2. Make sure your .NET version is higher or equal to 461814.

The agent is running on Windows server 2012R2, and we are using TFS 2018 on prem.
